=== zymk9/cmu15618_project/scripts/scene.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://yocto-gl.com/scene.schema.json",
  "title": "Yocto/GL Scene Format",
  "description": "The scene format used by Yocto/GL",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "asset": {
      "description": "asset information",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "version": {
          "description": "Version string",
          "type": "string",
          "enum": ["4.1", "4.2", "5.0"]
        },
        "copyright": {
          "description": "Copyright string",
          "type": "string"
        },
        "generator": {
          "description": "Generator string",
          "type": "string"
        }
      }
    },
    "cameras": {
      "description": "Scene cameras",
      "type": "array",
      "items": {
        "description": "Camera",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "frame": {
            "description": "Frame",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "lens": {
            "description": "Lens",
            "type": "number"
          },
          "film": {
            "description": "film size",
            "type": "number"
          },
          "aspect": {
            "description": "Aspect ratio",
            "type": "number"
          },
          "focus": {
            "description": "Focus distance",
            "type": "number"
          },
          "aperture": {
            "description": "Lens aperture",
            "type": "number"
          },
          "orthographic": {
            "description": "Whether the camera is orthographic",
            "type": "boolean"
          }
        }
      }
    },
    "textures": {
      "description": "Scene textures",
      "type": "array",
      "items": {
        "description": "Texture",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "uri": {
            "description": "Uri",
            "type": "string"
          }
        }
      }
    },
    "shapes": {
      "description": "Scene shapes",
      "type": "array",
      "items": {
        "description": "Shape",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "uri": {
            "description": "Uri",
            "type": "string"
          }
        }
      }
    },
    "materials": {
      "description": "Scene materials",
      "type": "array",
      "items": {
        "description": "Object",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "type": {
            "description": "Type",
            "type": "string",
            "enum": [
              "matte",
              "glossy",
              "reflective",
              "transparent",
              "refractive",
              "subsurface",
              "volume",
              "gltfpbr"
            ]
          },
          "emission": {
            "description": "Emission",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "color": {
            "description": "Color",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "roughness": {
            "description": "Roughness",
            "type": "number"
          },
          "metallic": {
            "description": "Metallic",
            "type": "number"
          },
          "ior": {
            "description": "Ior",
            "type": "number"
          },
          "scattering": {
            "description": "Volume scattering",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "scanisotropy": {
            "description": "Scattering anisotropy",
            "type": "number"
          },
          "trdepth": {
            "description": "Transmission depth",
            "type": "number"
          },
          "opacity": {
            "description": "Opacity",
            "type": "number"
          },
          "displacement": {
            "description": "Displacement",
            "type": "integer"
          },
          "emission_tex": {
            "description": "Emission map",
            "type": "integer"
          },
          "color_tex": {
            "description": "Color",
            "type": "integer"
          },
          "roughness_tex": {
            "description": "Roughness",
            "type": "integer"
          },
          "metallic_tex": {
            "description": "Metallic",
            "type": "integer"
          },
          "scattering_tex": {
            "description": "Volume scattering",
            "type": "integer"
          },
          "displacement_tex": {
            "description": "Displacement map",
            "type": "integer"
          },
          "normal_tex": {
            "description": "Normal map",
            "type": "integer"
          }
        }
      }
    },
    "instances": {
      "description": "Scene instances",
      "type": "array",
      "items": {
        "description": "Instance",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "frame": {
            "description": "Frame",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "shape": {
            "description": "Shape index",
            "type": "integer"
          },
          "material": {
            "description": "Material index",
            "type": "integer"
          }
        }
      }
    },
    "environments": {
      "description": "Scene environments",
      "type": "array",
      "items": {
        "description": "Environment",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "frame": {
            "description": "Frame",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "emission": {
            "description": "Emission",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "emission_tex": {
            "description": "Environment map index",
            "type": "integer"
          }
        }
      }
    },
    "subdivs": {
      "description": "Scene subdivs",
      "type": "array",
      "items": {
        "description": "Subdiv",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "uri": {
            "description": "Uri",
            "type": "string"
          },
          "shape": {
            "description": "Shape index",
            "type": "integer"
          },
          "subdivisions": {
            "description": "Subdivisions",
            "type": "integer"
          },
          "smooth": {
            "description": "Smooth normals",
            "type": "boolean"
          },
          "catmullclark": {
            "description": "Catmull-Clark subdivision",
            "type": "boolean"
          },
          "displacement": {
            "description": "Displacement amount",
            "type": "number"
          },
          "displacement_tex": {
            "description": "Displacement texture",
            "type": "integer"
          }
        }
      }
    }
  }
}

=== zymk9/cmu15618_project/tests/_version43/materials5/materials5.json
{
  "asset": {
    "copyright": "Model by Fabio Pellacini from github.com/~xelatihy/yocto-gl",
    "generator": "Yocto/GL - https://github.com/xelatihy/yocto-gl",
    "version": "4.2"
  },
  "cameras": [
    {
      "name": "default",
      "frame": [
        0.9805806875228882, -0.0, 0.1961161345243454, 0.08506310731172562,
        0.9010388255119324, -0.4253155291080475, -0.17670825123786926,
        0.43373844027519226, 0.8835412859916687, -0.6000000238418579, 1.5, 2.75
      ],
      "lens": 0.10000000149011612,
      "aspect": 2.4000000953674316,
      "focus": 3.1124749183654785
    },
    {
      "name": "front",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 0.8853979110717773, -0.46483391523361206, 0.0,
        0.46483391523361206, 0.8853979110717773, 0.0, 1.75, 3.0
      ],
      "lens": 0.10000000149011612,
      "aspect": 3.0,
      "focus": 3.3883070945739746
    },
    {
      "name": "back",
      "frame": [
        -1.0, 0.0, 0.0, 0.0, 0.9026037454605103, 0.4304725229740143, 0.0,
        0.4304724931716919, -0.9026036858558655, 0.0, 1.5, -3.25
      ],
      "lens": 0.10000000149011612,
      "aspect": 3.0,
      "focus": 3.600694417953491
    },
    {
      "name": "perspective-sharp",
      "frame": [
        0.9805806875228882, -0.0, 0.1961161345243454, 0.08506310731172562,
        0.9010388255119324, -0.4253155291080475, -0.17670825123786926,
        0.43373844027519226, 0.8835412859916687, -0.6000000238418579, 1.5, 2.75
      ],
      "lens": 0.10000000149011612,
      "aspect": 2.4000000953674316,
      "focus": 3.1124749183654785
    },
    {
      "name": "perspective-dof",
      "frame": [
        0.9805806875228882, -0.0, 0.1961161345243454, 0.08506310731172562,
        0.9010388255119324, -0.4253155291080475, -0.17670825123786926,
        0.43373844027519226, 0.8835412859916687, -0.6000000238418579, 1.5, 2.75
      ],
      "lens": 0.10000000149011612,
      "aspect": 2.4000000953674316,
      "focus": 3.1124749183654785,
      "aperture": 0.05000000074505806
    },
    {
      "name": "orthographic-sharp",
      "frame": [
        0.9756097197532654, -0.0, 0.2195121943950653, 0.08407647162675858,
        0.9237421154975891, -0.3736732006072998, -0.20277264714241028,
        0.3830150067806244, 0.9012117385864258, -0.5, 1.0, 2.0
      ],
      "orthographic": true,
      "lens": 0.029999999329447746,
      "aspect": 2.4000000953674316,
      "focus": 2.2192342281341553
    },
    {
      "name": "orthographic-dof",
      "frame": [
        0.9756097197532654, -0.0, 0.2195121943950653, 0.08407647162675858,
        0.9237421154975891, -0.3736732006072998, -0.20277264714241028,
        0.3830150067806244, 0.9012117385864258, -0.5, 1.0, 2.0
      ],
      "orthographic": true,
      "lens": 0.029999999329447746,
      "aspect": 2.4000000953674316,
      "focus": 2.2192342281341553,
      "aperture": 0.019999999552965164
    }
  ],
  "environments": [
    {
      "name": "sky",
      "emission": [0.5, 0.5, 0.5],
      "emission_tex": 0
    }
  ],
  "textures": [
    {
      "name": "sky",
      "uri": "textures/sky.hdr"
    },
    {
      "name": "floor",
      "uri": "textures/floor.png"
    }
  ],
  "materials": [
    {
      "name": "floor",
      "color": [0.699999988079071, 0.699999988079071, 0.699999988079071],
      "color_tex": 1
    },
    {
      "name": "largearealight1",
      "emission": [10.0, 10.0, 10.0]
    },
    {
      "name": "largearealight2",
      "emission": [10.0, 10.0, 10.0]
    },
    {
      "name": "skin1a",
      "type": "refractive",
      "color": [0.7599999904632568, 0.47999998927116394, 0.23000000417232513],
      "roughness": 0.25,
      "trdepth": 0.0010000000474974513,
      "scattering": [
        0.4359999895095825, 0.22699999809265137, 0.13099999725818634
      ],
      "scanisotropy": -0.800000011920929
    },
    {
      "name": "skin2a",
      "type": "refractive",
      "color": [0.8199999928474426, 0.550000011920929, 0.4000000059604645],
      "roughness": 0.25,
      "trdepth": 0.0010000000474974513,
      "scattering": [
        0.6230000257492065, 0.43299999833106995, 0.34299999475479126
      ],
      "scanisotropy": -0.800000011920929
    },
    {
      "name": "skins",
      "type": "refractive",
      "color": [0.7599999904632568, 0.47999998927116394, 0.23000000417232513],
      "trdepth": 0.0010000000474974513,
      "scattering": [
        0.4359999895095825, 0.22699999809265137, 0.13099999725818634
      ],
      "scanisotropy": -0.800000011920929
    },
    {
      "name": "skin1b",
      "type": "refractive",
      "color": [0.7599999904632568, 0.47999998927116394, 0.23000000417232513],
      "roughness": 0.25,
      "trdepth": 0.0010000000474974513,
      "scattering": [
        0.4359999895095825, 0.22699999809265137, 0.13099999725818634
      ],
      "scanisotropy": -0.800000011920929
    },
    {
      "name": "skin2b",
      "type": "refractive",
      "color": [0.8199999928474426, 0.550000011920929, 0.4000000059604645],
      "roughness": 0.25,
      "trdepth": 0.0010000000474974513,
      "scattering": [
        0.6230000257492065, 0.43299999833106995, 0.34299999475479126
      ],
      "scanisotropy": -0.800000011920929
    }
  ],
  "shapes": [
    {
      "name": "floor",
      "uri": "shapes/floor.ply"
    },
    {
      "name": "largearealight1",
      "uri": "shapes/largearealight1.ply"
    },
    {
      "name": "largearealight2",
      "uri": "shapes/largearealight2.ply"
    },
    {
      "name": "sphere",
      "uri": "shapes/sphere.ply"
    },
    {
      "name": "bunny",
      "uri": "shapes/bunny.ply"
    }
  ],
  "instances": [
    {
      "name": "floor",
      "shape": 0,
      "material": 0
    },
    {
      "name": "largearealight1",
      "frame": [
        0.8944271802902222, -0.0, 0.4472135901451111, 0.2873478829860687,
        0.766261100769043, -0.5746957659721375, -0.3426823318004608,
        0.6425293684005737, 0.6853646636009216, -0.800000011920929,
        1.600000023841858, 1.600000023841858
      ],
      "shape": 1,
      "material": 1
    },
    {
      "name": "largearealight2",
      "frame": [
        0.8944271802902222, 0.0, -0.4472135901451111, -0.2873478829860687,
        0.766261100769043, -0.5746957659721375, 0.3426823318004608,
        0.6425293684005737, 0.6853646636009216, 0.800000011920929,
        1.600000023841858, 1.600000023841858
      ],
      "shape": 2,
      "material": 2
    },
    {
      "name": "sphere-skin1a",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -0.4000000059604645, 0.0,
        0.0
      ],
      "shape": 3,
      "material": 3
    },
    {
      "name": "sphere-skin2a",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -0.20000000298023224, 0.0,
        0.0
      ],
      "shape": 3,
      "material": 4
    },
    {
      "name": "sphere-skins",
      "shape": 3,
      "material": 5
    },
    {
      "name": "sphere-skin1b",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.20000000298023224, 0.0,
        0.0
      ],
      "shape": 3,
      "material": 6
    },
    {
      "name": "sphere-skin2b",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.4000000059604645, 0.0,
        0.0
      ],
      "shape": 3,
      "material": 7
    },
    {
      "name": "bunny-skin1a",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -0.4000000059604645, 0.0,
        -0.4000000059604645
      ],
      "shape": 4,
      "material": 3
    },
    {
      "name": "bunny-skin2a",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -0.20000000298023224, 0.0,
        -0.4000000059604645
      ],
      "shape": 4,
      "material": 4
    },
    {
      "name": "bunny-skins",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        -0.4000000059604645
      ],
      "shape": 4,
      "material": 5
    },
    {
      "name": "bunny-skin1b",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.20000000298023224, 0.0,
        -0.4000000059604645
      ],
      "shape": 4,
      "material": 6
    },
    {
      "name": "bunny-skin2b",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.4000000059604645, 0.0,
        -0.4000000059604645
      ],
      "shape": 4,
      "material": 7
    }
  ]
}
