=== zymk9/cmu15618_project/scripts/scene.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://yocto-gl.com/scene.schema.json",
  "title": "Yocto/GL Scene Format",
  "description": "The scene format used by Yocto/GL",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "asset": {
      "description": "asset information",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "version": {
          "description": "Version string",
          "type": "string",
          "enum": ["4.1", "4.2", "5.0"]
        },
        "copyright": {
          "description": "Copyright string",
          "type": "string"
        },
        "generator": {
          "description": "Generator string",
          "type": "string"
        }
      }
    },
    "cameras": {
      "description": "Scene cameras",
      "type": "array",
      "items": {
        "description": "Camera",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "frame": {
            "description": "Frame",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "lens": {
            "description": "Lens",
            "type": "number"
          },
          "film": {
            "description": "film size",
            "type": "number"
          },
          "aspect": {
            "description": "Aspect ratio",
            "type": "number"
          },
          "focus": {
            "description": "Focus distance",
            "type": "number"
          },
          "aperture": {
            "description": "Lens aperture",
            "type": "number"
          },
          "orthographic": {
            "description": "Whether the camera is orthographic",
            "type": "boolean"
          }
        }
      }
    },
    "textures": {
      "description": "Scene textures",
      "type": "array",
      "items": {
        "description": "Texture",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "uri": {
            "description": "Uri",
            "type": "string"
          }
        }
      }
    },
    "shapes": {
      "description": "Scene shapes",
      "type": "array",
      "items": {
        "description": "Shape",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "uri": {
            "description": "Uri",
            "type": "string"
          }
        }
      }
    },
    "materials": {
      "description": "Scene materials",
      "type": "array",
      "items": {
        "description": "Object",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "type": {
            "description": "Type",
            "type": "string",
            "enum": [
              "matte",
              "glossy",
              "reflective",
              "transparent",
              "refractive",
              "subsurface",
              "volume",
              "gltfpbr"
            ]
          },
          "emission": {
            "description": "Emission",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "color": {
            "description": "Color",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "roughness": {
            "description": "Roughness",
            "type": "number"
          },
          "metallic": {
            "description": "Metallic",
            "type": "number"
          },
          "ior": {
            "description": "Ior",
            "type": "number"
          },
          "scattering": {
            "description": "Volume scattering",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "scanisotropy": {
            "description": "Scattering anisotropy",
            "type": "number"
          },
          "trdepth": {
            "description": "Transmission depth",
            "type": "number"
          },
          "opacity": {
            "description": "Opacity",
            "type": "number"
          },
          "displacement": {
            "description": "Displacement",
            "type": "integer"
          },
          "emission_tex": {
            "description": "Emission map",
            "type": "integer"
          },
          "color_tex": {
            "description": "Color",
            "type": "integer"
          },
          "roughness_tex": {
            "description": "Roughness",
            "type": "integer"
          },
          "metallic_tex": {
            "description": "Metallic",
            "type": "integer"
          },
          "scattering_tex": {
            "description": "Volume scattering",
            "type": "integer"
          },
          "displacement_tex": {
            "description": "Displacement map",
            "type": "integer"
          },
          "normal_tex": {
            "description": "Normal map",
            "type": "integer"
          }
        }
      }
    },
    "instances": {
      "description": "Scene instances",
      "type": "array",
      "items": {
        "description": "Instance",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "frame": {
            "description": "Frame",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "shape": {
            "description": "Shape index",
            "type": "integer"
          },
          "material": {
            "description": "Material index",
            "type": "integer"
          }
        }
      }
    },
    "environments": {
      "description": "Scene environments",
      "type": "array",
      "items": {
        "description": "Environment",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "frame": {
            "description": "Frame",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "emission": {
            "description": "Emission",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "emission_tex": {
            "description": "Environment map index",
            "type": "integer"
          }
        }
      }
    },
    "subdivs": {
      "description": "Scene subdivs",
      "type": "array",
      "items": {
        "description": "Subdiv",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "uri": {
            "description": "Uri",
            "type": "string"
          },
          "shape": {
            "description": "Shape index",
            "type": "integer"
          },
          "subdivisions": {
            "description": "Subdivisions",
            "type": "integer"
          },
          "smooth": {
            "description": "Smooth normals",
            "type": "boolean"
          },
          "catmullclark": {
            "description": "Catmull-Clark subdivision",
            "type": "boolean"
          },
          "displacement": {
            "description": "Displacement amount",
            "type": "number"
          },
          "displacement_tex": {
            "description": "Displacement texture",
            "type": "integer"
          }
        }
      }
    }
  }
}

=== zymk9/cmu15618_project/tests/materials4/materials4.json
{
  "asset": {
    "copyright": "Model by Fabio Pellacini from github.com/~xelatihy/yocto-gl",
    "generator": "Yocto/GL - https://github.com/xelatihy/yocto-gl",
    "version": "4.2"
  },
  "cameras": [
    {
      "name": "default",
      "frame": [
        0.8151804208755493,
        -0.0,
        0.579207181930542,
        0.16660168766975403,
        0.9577393531799316,
        -0.23447643220424652,
        -0.5547295212745667,
        0.28763750195503235,
        0.7807304263114929,
        -0.75,
        0.4000000059604645,
        0.8999999761581421
      ],
      "aspect": 2.4000000953674316,
      "focus": 1.2168092727661133
    }
  ],
  "environments": [
    {
      "name": "sky",
      "emission": [
        0.5,
        0.5,
        0.5
      ],
      "emission_tex": 0
    }
  ],
  "textures": [
    {
      "name": "sky",
      "uri": "textures/sky.hdr"
    },
    {
      "name": "floor",
      "uri": "textures/floor.png"
    }
  ],
  "shapes": [
    {
      "name": "largearealight1",
      "uri": "shapes/largearealight1.ply"
    },
    {
      "name": "largearealight2",
      "uri": "shapes/largearealight2.ply"
    },
    {
      "name": "floor",
      "uri": "shapes/floor.ply"
    },
    {
      "name": "sphere",
      "uri": "shapes/sphere.ply"
    }
  ],
  "subdivs": [],
  "materials": [
    {
      "name": "largearealight1",
      "type": "matte",
      "emission": [
        10,
        10,
        10
      ],
      "color": [
        0,
        0,
        0
      ]
    },
    {
      "name": "largearealight2",
      "type": "matte",
      "emission": [
        10,
        10,
        10
      ],
      "color": [
        0,
        0,
        0
      ]
    },
    {
      "name": "floor",
      "type": "matte",
      "color": [
        1,
        1,
        1
      ],
      "color_tex": 1
    },
    {
      "name": "cloud",
      "type": "volume",
      "color": [
        0.5,
        0.5,
        0.5
      ],
      "roughness": 0,
      "scattering": [
        0.9,
        0.9,
        0.9
      ]
    },
    {
      "name": "redglass",
      "type": "refractive",
      "color": [
        1.0,
        0.5,
        0.5
      ],
      "roughness": 0
    },
    {
      "name": "glass",
      "type": "refractive",
      "color": [
        1.0,
        1.0,
        1.0
      ],
      "roughness": 0
    },
    {
      "name": "jade",
      "type": "refractive",
      "color": [
        0.5,
        0.5,
        0.5
      ],
      "roughness": 0,
      "scattering": [
        0.3,
        0.6,
        0.3
      ]
    },
    {
      "name": "smoke",
      "type": "volume",
      "color": [
        0.65,
        0.65,
        0.65
      ],
      "roughness": 0,
      "scattering": [
        0.2,
        0.2,
        0.2
      ]
    }
  ],
  "instances": [
    {
      "name": "largearealight1",
      "frame": [
        0.8944271802902222,
        -0.0,
        0.4472135901451111,
        0.2873478829860687,
        0.766261100769043,
        -0.5746957659721375,
        -0.3426823318004608,
        0.6425293684005737,
        0.6853646636009216,
        -0.800000011920929,
        1.600000023841858,
        1.600000023841858
      ],
      "shape": 0,
      "material": 0
    },
    {
      "name": "largearealight2",
      "frame": [
        0.8944271802902222,
        0.0,
        -0.4472135901451111,
        -0.2873478829860687,
        0.766261100769043,
        -0.5746957659721375,
        0.3426823318004608,
        0.6425293684005737,
        0.6853646636009216,
        0.800000011920929,
        1.600000023841858,
        1.600000023841858
      ],
      "shape": 1,
      "material": 1
    },
    {
      "name": "floor",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0
      ],
      "shape": 2,
      "material": 2
    },
    {
      "name": "sphere-cloud",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        -0.4,
        0,
        0
      ],
      "shape": 3,
      "material": 3
    },
    {
      "name": "sphere-redglass",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        -0.2,
        0,
        0
      ],
      "shape": 3,
      "material": 4
    },
    {
      "name": "sphere-glass",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.0,
        0,
        0
      ],
      "shape": 3,
      "material": 5
    },
    {
      "name": "sphere-jade",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.2,
        0,
        0
      ],
      "shape": 3,
      "material": 6
    },
    {
      "name": "sphere-smoke",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.4,
        0,
        0
      ],
      "shape": 3,
      "material": 7
    }
  ]
}

=== zymk9/cmu15618_project/tests/materials2/materials2.json
{
  "asset": {
    "copyright": "Model by Fabio Pellacini from github.com/~xelatihy/yocto-gl",
    "generator": "Yocto/GL - https://github.com/xelatihy/yocto-gl",
    "version": "4.2"
  },
  "cameras": [
    {
      "name": "default",
      "frame": [
        0.8151804208755493,
        -0.0,
        0.579207181930542,
        0.16660168766975403,
        0.9577393531799316,
        -0.23447643220424652,
        -0.5547295212745667,
        0.28763750195503235,
        0.7807304263114929,
        -0.75,
        0.4000000059604645,
        0.8999999761581421
      ],
      "aspect": 2.4000000953674316,
      "focus": 1.2168092727661133
    }
  ],
  "environments": [
    {
      "name": "sky",
      "emission": [
        0.5,
        0.5,
        0.5
      ],
      "emission_tex": 0
    }
  ],
  "textures": [
    {
      "name": "sky",
      "uri": "textures/sky.hdr"
    },
    {
      "name": "floor",
      "uri": "textures/floor.png"
    }
  ],
  "shapes": [
    {
      "name": "largearealight1",
      "uri": "shapes/largearealight1.ply"
    },
    {
      "name": "largearealight2",
      "uri": "shapes/largearealight2.ply"
    },
    {
      "name": "floor",
      "uri": "shapes/floor.ply"
    },
    {
      "name": "sphere",
      "uri": "shapes/sphere.ply"
    }
  ],
  "subdivs": [],
  "materials": [
    {
      "name": "largearealight1",
      "type": "matte",
      "emission": [
        10,
        10,
        10
      ],
      "color": [
        0,
        0,
        0
      ]
    },
    {
      "name": "largearealight2",
      "type": "matte",
      "emission": [
        10,
        10,
        10
      ],
      "color": [
        0,
        0,
        0
      ]
    },
    {
      "name": "floor",
      "type": "matte",
      "color": [
        1,
        1,
        1
      ],
      "color_tex": 1
    },
    {
      "name": "sharpglass",
      "type": "refractive",
      "color": [
        1.0,
        1.0,
        1.0
      ],
      "roughness": 0
    },
    {
      "name": "roughglass",
      "type": "refractive",
      "color": [
        1.0,
        0.7,
        0.7
      ],
      "roughness": 0.1
    },
    {
      "name": "notopaque",
      "type": "matte",
      "color": [
        0.7,
        0.5,
        0.5
      ],
      "opacity": 0.2,
      "roughness": 0.1
    },
    {
      "name": "sharpthinglass",
      "type": "transparent",
      "color": [
        1.0,
        1.0,
        1.0
      ],
      "roughness": 0
    },
    {
      "name": "roughthinglass",
      "type": "transparent",
      "color": [
        1.0,
        0.7,
        0.7
      ],
      "roughness": 0.1
    }
  ],
  "instances": [
    {
      "name": "largearealight1",
      "frame": [
        0.8944271802902222,
        -0.0,
        0.4472135901451111,
        0.2873478829860687,
        0.766261100769043,
        -0.5746957659721375,
        -0.3426823318004608,
        0.6425293684005737,
        0.6853646636009216,
        -0.800000011920929,
        1.600000023841858,
        1.600000023841858
      ],
      "shape": 0,
      "material": 0
    },
    {
      "name": "largearealight2",
      "frame": [
        0.8944271802902222,
        0.0,
        -0.4472135901451111,
        -0.2873478829860687,
        0.766261100769043,
        -0.5746957659721375,
        0.3426823318004608,
        0.6425293684005737,
        0.6853646636009216,
        0.800000011920929,
        1.600000023841858,
        1.600000023841858
      ],
      "shape": 1,
      "material": 1
    },
    {
      "name": "floor",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0
      ],
      "shape": 2,
      "material": 2
    },
    {
      "name": "sphere-sharpglass",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        -0.4,
        0,
        0
      ],
      "shape": 3,
      "material": 3
    },
    {
      "name": "sphere-roughglass",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        -0.2,
        0,
        0
      ],
      "shape": 3,
      "material": 4
    },
    {
      "name": "sphere-notopaque",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.0,
        0,
        0
      ],
      "shape": 3,
      "material": 5
    },
    {
      "name": "sphere-sharpthinglass",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.2,
        0,
        0
      ],
      "shape": 3,
      "material": 6
    },
    {
      "name": "sphere-roughthinglass",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.4,
        0,
        0
      ],
      "shape": 3,
      "material": 7
    }
  ]
}

=== zymk9/cmu15618_project/tests/_version43/furnace1/furnace1.json
{
  "asset": {
    "copyright": "Model by Fabio Pellacini from github.com/~xelatihy/yocto-gl",
    "generator": "Yocto/GL - https://github.com/xelatihy/yocto-gl",
    "version": "4.2"
  },
  "cameras": [
    {
      "name": "default",
      "frame": [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0],
      "aspect": 2.4000000953674316,
      "focus": 1.0
    }
  ],
  "environments": [
    {
      "name": "env",
      "emission": [0.5, 0.5, 0.5]
    }
  ],
  "materials": [
    {
      "name": "sphere",
      "type": "reflective",
      "color": [1.0, 1.0, 1.0],
      "roughness": 0.5
    }
  ],
  "shapes": [
    {
      "name": "sphere",
      "uri": "shapes/sphere.ply"
    }
  ],
  "instances": [
    {
      "name": "sphere",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, -0.07500000298023224,
        0.0
      ],
      "shape": 0,
      "material": 0
    }
  ]
}

=== zymk9/cmu15618_project/tests/_version43/furnace2/furnace2.json
{
  "asset": {
    "copyright": "Model by Fabio Pellacini from github.com/~xelatihy/yocto-gl",
    "version": "4.2"
  },
  "cameras": [
    {
      "name": "default",
      "lens": 0.1,
      "aperture": 0.0,
      "aspect": 1,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.075, 3]
    }
  ],
  "environments": [
    {
      "name": "furnace",
      "emission": [0.5, 0.5, 0.5]
    }
  ],
  "materials": [
    {
      "name": "metallic-0",
      "type": "reflective",
      "color": [1, 1, 1],
      "roughness": 0
    },
    {
      "name": "metallic-0.25",
      "type": "reflective",
      "color": [1, 1, 1],
      "roughness": 0.25
    },
    {
      "name": "metallic-0.5",
      "type": "reflective",
      "color": [1, 1, 1],
      "roughness": 0.5
    },
    {
      "name": "metallic-0.75",
      "type": "reflective",
      "color": [1, 1, 1],
      "roughness": 0.75
    },
    {
      "name": "metallic-1",
      "type": "reflective",
      "color": [1, 1, 1],
      "roughness": 1
    },
    {
      "name": "transparent-0",
      "type": "transparent",
      "color": [1, 1, 1],
      "roughness": 0
    },
    {
      "name": "transparent-0.25",
      "type": "transparent",
      "color": [1, 1, 1],
      "roughness": 0.25
    },
    {
      "name": "transparent-0.5",
      "type": "transparent",
      "color": [1, 1, 1],
      "roughness": 0.5
    },
    {
      "name": "transparent-0.75",
      "type": "transparent",
      "color": [1, 1, 1],
      "roughness": 0.75
    },
    {
      "name": "transparent-1",
      "type": "transparent",
      "color": [1, 1, 1],
      "roughness": 1
    },
    {
      "name": "refractive-0",
      "type": "refractive",
      "color": [1, 1, 1],
      "roughness": 0
    },
    {
      "name": "refractive-0.25",
      "type": "refractive",
      "color": [1, 1, 1],
      "roughness": 0.25
    },
    {
      "name": "refractive-0.5",
      "type": "refractive",
      "color": [1, 1, 1],
      "roughness": 0.5
    },
    {
      "name": "refractive-0.75",
      "type": "refractive",
      "color": [1, 1, 1],
      "roughness": 0.75
    },
    {
      "name": "refractive-1",
      "type": "refractive",
      "color": [1, 1, 1],
      "roughness": 1
    },
    {
      "name": "matte-0",
      "type": "matte",
      "color": [1, 1, 1],
      "roughness": 0
    },
    {
      "name": "matte-0.25",
      "type": "matte",
      "color": [1, 1, 1],
      "roughness": 0.25
    },
    {
      "name": "matte-0.5",
      "type": "matte",
      "color": [1, 1, 1],
      "roughness": 0.5
    },
    {
      "name": "matte-0.75",
      "type": "matte",
      "color": [1, 1, 1],
      "roughness": 0.75
    },
    {
      "name": "matte-1",
      "type": "matte",
      "color": [1, 1, 1],
      "roughness": 1
    },
    {
      "name": "glossy-0",
      "type": "glossy",
      "color": [1, 1, 1],
      "roughness": 0
    },
    {
      "name": "glossy-0.25",
      "type": "glossy",
      "color": [1, 1, 1],
      "roughness": 0.25
    },
    {
      "name": "glossy-0.5",
      "type": "glossy",
      "color": [1, 1, 1],
      "roughness": 0.5
    },
    {
      "name": "glossy-0.75",
      "type": "glossy",
      "color": [1, 1, 1],
      "roughness": 0.75
    },
    {
      "name": "glossy-1",
      "type": "glossy",
      "color": [1, 1, 1],
      "roughness": 1
    }
  ],
  "shapes": [
    {
      "name": "sphere",
      "uri": "shapes/sphere.ply"
    }
  ],
  "instances": [
    {
      "name": "metallic-0",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, -0.4, 0.4, 0],
      "material": 0
    },
    {
      "name": "metallic-0.25",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, -0.2, 0.4, 0],
      "material": 1
    },
    {
      "name": "metallic-0.5",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.4, 0],
      "material": 2
    },
    {
      "name": "metallic-0.75",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0.2, 0.4, 0],
      "material": 3
    },
    {
      "name": "metallic-1",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0.4, 0.4, 0],
      "material": 4
    },
    {
      "name": "transparent-0",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, -0.4, 0.2, 0],
      "material": 5
    },
    {
      "name": "transparent-0.25",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, -0.2, 0.2, 0],
      "material": 6
    },
    {
      "name": "transparent-0.5",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.2, 0],
      "material": 7
    },
    {
      "name": "transparent-0.75",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0.2, 0.2, 0],
      "material": 8
    },
    {
      "name": "transparent-1",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0.4, 0.2, 0],
      "material": 9
    },
    {
      "name": "refractive-0",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, -0.4, 0, 0],
      "material": 10
    },
    {
      "name": "refractive-0.25",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, -0.2, 0, 0],
      "material": 11
    },
    {
      "name": "refractive-0.5",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
      "material": 12
    },
    {
      "name": "refractive-0.75",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0.2, 0, 0],
      "material": 13
    },
    {
      "name": "refractive-1",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0.4, 0, 0],
      "material": 14
    },
    {
      "name": "matte-0",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, -0.4, -0.2, 0],
      "material": 15
    },
    {
      "name": "matte-0.25",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, -0.2, -0.2, 0],
      "material": 16
    },
    {
      "name": "matte-0.5",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.2, 0],
      "material": 17
    },
    {
      "name": "matte-0.75",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0.2, -0.2, 0],
      "material": 18
    },
    {
      "name": "matte-1",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0.4, -0.2, 0],
      "material": 19
    },
    {
      "name": "glossy-0",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, -0.4, -0.4, 0],
      "material": 20
    },
    {
      "name": "glossy-0.25",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, -0.2, -0.4, 0],
      "material": 21
    },
    {
      "name": "glossy-0.5",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.4, 0],
      "material": 22
    },
    {
      "name": "glossy-0.75",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0.2, -0.4, 0],
      "material": 23
    },
    {
      "name": "glossy-1",
      "shape": 0,
      "frame": [1, 0, 0, 0, 1, 0, 0, 0, 1, 0.4, -0.4, 0],
      "material": 24
    }
  ]
}

=== zymk9/cmu15618_project/tests/_version43/cornellbox/cornellbox.json
{
  "asset": {
    "generator": "Yocto/GL - https://github.com/xelatihy/yocto-gl",
    "version": "4.2"
  },
  "cameras": [
    {
      "name": "camera1",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0,
        3.9000000953674316
      ],
      "lens": 0.03500000014901161,
      "aspect": 1.0,
      "film": 0.024000000208616257,
      "focus": 3.9000000953674316
    }
  ],
  "materials": [
    {
      "name": "backwall",
      "color": [0.7250000238418579, 0.7099999785423279, 0.6800000071525574]
    },
    {
      "name": "ceiling",
      "color": [0.7250000238418579, 0.7099999785423279, 0.6800000071525574]
    },
    {
      "name": "floor",
      "color": [0.7250000238418579, 0.7099999785423279, 0.6800000071525574]
    },
    {
      "name": "leftwall",
      "color": [0.6299999952316284, 0.06499999761581421, 0.05000000074505806]
    },
    {
      "name": "light",
      "emission": [17.0, 12.0, 4.0]
    },
    {
      "name": "rightwall",
      "color": [0.14000000059604645, 0.44999998807907104, 0.09000000357627869]
    },
    {
      "name": "shortbox",
      "color": [0.7250000238418579, 0.7099999785423279, 0.6800000071525574]
    },
    {
      "name": "tallbox",
      "color": [0.7250000238418579, 0.7099999785423279, 0.6800000071525574]
    }
  ],
  "shapes": [
    {
      "name": "backwall",
      "uri": "shapes/backwall.ply"
    },
    {
      "name": "ceiling",
      "uri": "shapes/ceiling.ply"
    },
    {
      "name": "floor",
      "uri": "shapes/floor.ply"
    },
    {
      "name": "leftwall",
      "uri": "shapes/leftwall.ply"
    },
    {
      "name": "light",
      "uri": "shapes/light.ply"
    },
    {
      "name": "rightwall",
      "uri": "shapes/rightwall.ply"
    },
    {
      "name": "shortbox",
      "uri": "shapes/shortbox.ply"
    },
    {
      "name": "tallbox",
      "uri": "shapes/tallbox.ply"
    }
  ],
  "instances": [
    {
      "name": "backwall",
      "shape": 0,
      "material": 0
    },
    {
      "name": "ceiling",
      "shape": 1,
      "material": 1
    },
    {
      "name": "floor",
      "shape": 2,
      "material": 2
    },
    {
      "name": "leftwall",
      "shape": 3,
      "material": 3
    },
    {
      "name": "light",
      "shape": 4,
      "material": 4
    },
    {
      "name": "rightwall",
      "shape": 5,
      "material": 5
    },
    {
      "name": "shortbox",
      "shape": 6,
      "material": 6
    },
    {
      "name": "tallbox",
      "shape": 7,
      "material": 7
    }
  ]
}
