=== zymk9/cmu15618_project/scripts/scene.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://yocto-gl.com/scene.schema.json",
  "title": "Yocto/GL Scene Format",
  "description": "The scene format used by Yocto/GL",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "asset": {
      "description": "asset information",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "version": {
          "description": "Version string",
          "type": "string",
          "enum": ["4.1", "4.2", "5.0"]
        },
        "copyright": {
          "description": "Copyright string",
          "type": "string"
        },
        "generator": {
          "description": "Generator string",
          "type": "string"
        }
      }
    },
    "cameras": {
      "description": "Scene cameras",
      "type": "array",
      "items": {
        "description": "Camera",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "frame": {
            "description": "Frame",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "lens": {
            "description": "Lens",
            "type": "number"
          },
          "film": {
            "description": "film size",
            "type": "number"
          },
          "aspect": {
            "description": "Aspect ratio",
            "type": "number"
          },
          "focus": {
            "description": "Focus distance",
            "type": "number"
          },
          "aperture": {
            "description": "Lens aperture",
            "type": "number"
          },
          "orthographic": {
            "description": "Whether the camera is orthographic",
            "type": "boolean"
          }
        }
      }
    },
    "textures": {
      "description": "Scene textures",
      "type": "array",
      "items": {
        "description": "Texture",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "uri": {
            "description": "Uri",
            "type": "string"
          }
        }
      }
    },
    "shapes": {
      "description": "Scene shapes",
      "type": "array",
      "items": {
        "description": "Shape",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "uri": {
            "description": "Uri",
            "type": "string"
          }
        }
      }
    },
    "materials": {
      "description": "Scene materials",
      "type": "array",
      "items": {
        "description": "Object",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "type": {
            "description": "Type",
            "type": "string",
            "enum": [
              "matte",
              "glossy",
              "reflective",
              "transparent",
              "refractive",
              "subsurface",
              "volume",
              "gltfpbr"
            ]
          },
          "emission": {
            "description": "Emission",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "color": {
            "description": "Color",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "roughness": {
            "description": "Roughness",
            "type": "number"
          },
          "metallic": {
            "description": "Metallic",
            "type": "number"
          },
          "ior": {
            "description": "Ior",
            "type": "number"
          },
          "scattering": {
            "description": "Volume scattering",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "scanisotropy": {
            "description": "Scattering anisotropy",
            "type": "number"
          },
          "trdepth": {
            "description": "Transmission depth",
            "type": "number"
          },
          "opacity": {
            "description": "Opacity",
            "type": "number"
          },
          "displacement": {
            "description": "Displacement",
            "type": "integer"
          },
          "emission_tex": {
            "description": "Emission map",
            "type": "integer"
          },
          "color_tex": {
            "description": "Color",
            "type": "integer"
          },
          "roughness_tex": {
            "description": "Roughness",
            "type": "integer"
          },
          "metallic_tex": {
            "description": "Metallic",
            "type": "integer"
          },
          "scattering_tex": {
            "description": "Volume scattering",
            "type": "integer"
          },
          "displacement_tex": {
            "description": "Displacement map",
            "type": "integer"
          },
          "normal_tex": {
            "description": "Normal map",
            "type": "integer"
          }
        }
      }
    },
    "instances": {
      "description": "Scene instances",
      "type": "array",
      "items": {
        "description": "Instance",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "frame": {
            "description": "Frame",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "shape": {
            "description": "Shape index",
            "type": "integer"
          },
          "material": {
            "description": "Material index",
            "type": "integer"
          }
        }
      }
    },
    "environments": {
      "description": "Scene environments",
      "type": "array",
      "items": {
        "description": "Environment",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "frame": {
            "description": "Frame",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "emission": {
            "description": "Emission",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "emission_tex": {
            "description": "Environment map index",
            "type": "integer"
          }
        }
      }
    },
    "subdivs": {
      "description": "Scene subdivs",
      "type": "array",
      "items": {
        "description": "Subdiv",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "description": "Name",
            "type": "string"
          },
          "uri": {
            "description": "Uri",
            "type": "string"
          },
          "shape": {
            "description": "Shape index",
            "type": "integer"
          },
          "subdivisions": {
            "description": "Subdivisions",
            "type": "integer"
          },
          "smooth": {
            "description": "Smooth normals",
            "type": "boolean"
          },
          "catmullclark": {
            "description": "Catmull-Clark subdivision",
            "type": "boolean"
          },
          "displacement": {
            "description": "Displacement amount",
            "type": "number"
          },
          "displacement_tex": {
            "description": "Displacement texture",
            "type": "integer"
          }
        }
      }
    }
  }
}

=== zymk9/cmu15618_project/tests/shapes1/shapes1.json
{
  "asset": {
    "copyright": "Model by Fabio Pellacini from github.com/~xelatihy/yocto-gl",
    "generator": "Yocto/GL - https://github.com/xelatihy/yocto-gl",
    "version": "4.2"
  },
  "cameras": [
    {
      "name": "default",
      "frame": [
        0.8151804208755493,
        -0.0,
        0.579207181930542,
        0.16660168766975403,
        0.9577393531799316,
        -0.23447643220424652,
        -0.5547295212745667,
        0.28763750195503235,
        0.7807304263114929,
        -0.75,
        0.4000000059604645,
        0.8999999761581421
      ],
      "aspect": 2.4000000953674316,
      "focus": 1.2168092727661133
    }
  ],
  "environments": [
    {
      "name": "sky",
      "emission": [
        0.5,
        0.5,
        0.5
      ],
      "emission_tex": 0
    }
  ],
  "textures": [
    {
      "name": "sky",
      "uri": "textures/sky.hdr"
    },
    {
      "name": "floor",
      "uri": "textures/floor.png"
    },
    {
      "name": "uvgrid",
      "uri": "textures/uvgrid.png"
    }
  ],
  "shapes": [
    {
      "name": "arealight1",
      "uri": "shapes/arealight1.ply"
    },
    {
      "name": "arealight2",
      "uri": "shapes/arealight2.ply"
    },
    {
      "name": "floor",
      "uri": "shapes/floor.ply"
    },
    {
      "name": "sphere",
      "uri": "shapes/sphere.ply"
    },
    {
      "name": "flipcapuvsphere",
      "uri": "shapes/flipcapuvsphere.ply"
    },
    {
      "name": "disk",
      "uri": "shapes/disk.ply"
    },
    {
      "name": "uvcylinder",
      "uri": "shapes/uvcylinder.ply"
    },
    {
      "name": "cube",
      "uri": "shapes/cube.ply"
    }
  ],
  "subdivs": [],
  "materials": [
    {
      "name": "arealight1",
      "type": "matte",
      "emission": [
        20,
        20,
        20
      ],
      "color": [
        0,
        0,
        0
      ]
    },
    {
      "name": "arealight2",
      "type": "matte",
      "emission": [
        20,
        20,
        20
      ],
      "color": [
        0,
        0,
        0
      ]
    },
    {
      "name": "floor",
      "type": "matte",
      "color": [
        1,
        1,
        1
      ],
      "color_tex": 1
    },
    {
      "name": "uvgrid",
      "type": "glossy",
      "color": [
        1,
        1,
        1
      ],
      "roughness": 0.2,
      "color_tex": 2
    }
  ],
  "instances": [
    {
      "name": "arealight1",
      "frame": [
        0.8944271802902222,
        -0.0,
        0.4472135901451111,
        0.27562475204467773,
        0.7874992489814758,
        -0.5512495040893555,
        -0.3521803617477417,
        0.6163156628608704,
        0.7043607234954834,
        -0.4000000059604645,
        0.800000011920929,
        0.800000011920929
      ],
      "shape": 0,
      "material": 0
    },
    {
      "name": "arealight2",
      "frame": [
        0.8944271802902222,
        0.0,
        -0.4472135901451111,
        -0.27562475204467773,
        0.7874992489814758,
        -0.5512495040893555,
        0.3521803617477417,
        0.6163156628608704,
        0.7043607234954834,
        0.4000000059604645,
        0.800000011920929,
        0.800000011920929
      ],
      "shape": 1,
      "material": 1
    },
    {
      "name": "floor",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0
      ],
      "shape": 2,
      "material": 2
    },
    {
      "name": "sphere-uvgrid",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        -0.4,
        0,
        0
      ],
      "shape": 3,
      "material": 3
    },
    {
      "name": "flipcapuvsphere-uvgrid",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        -0.2,
        0,
        0
      ],
      "shape": 4,
      "material": 3
    },
    {
      "name": "disk-uvgrid",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.0,
        0,
        0
      ],
      "shape": 5,
      "material": 3
    },
    {
      "name": "uvcylinder-uvgrid",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.2,
        0,
        0
      ],
      "shape": 6,
      "material": 3
    },
    {
      "name": "cube-uvgrid",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.4,
        0,
        0
      ],
      "shape": 7,
      "material": 3
    }
  ]
}

=== zymk9/cmu15618_project/tests/_version43/materials4/materials4.json
{
  "asset": {
    "copyright": "Model by Fabio Pellacini from github.com/~xelatihy/yocto-gl",
    "generator": "Yocto/GL - https://github.com/xelatihy/yocto-gl",
    "version": "4.2"
  },
  "cameras": [
    {
      "name": "default",
      "frame": [
        0.9805806875228882, -0.0, 0.1961161345243454, 0.08506310731172562,
        0.9010388255119324, -0.4253155291080475, -0.17670825123786926,
        0.43373844027519226, 0.8835412859916687, -0.6000000238418579, 1.5, 2.75
      ],
      "lens": 0.10000000149011612,
      "aspect": 2.4000000953674316,
      "focus": 3.1124749183654785
    },
    {
      "name": "front",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 0.8853979110717773, -0.46483391523361206, 0.0,
        0.46483391523361206, 0.8853979110717773, 0.0, 1.75, 3.0
      ],
      "lens": 0.10000000149011612,
      "aspect": 3.0,
      "focus": 3.3883070945739746
    },
    {
      "name": "back",
      "frame": [
        -1.0, 0.0, 0.0, 0.0, 0.9026037454605103, 0.4304725229740143, 0.0,
        0.4304724931716919, -0.9026036858558655, 0.0, 1.5, -3.25
      ],
      "lens": 0.10000000149011612,
      "aspect": 3.0,
      "focus": 3.600694417953491
    },
    {
      "name": "perspective-sharp",
      "frame": [
        0.9805806875228882, -0.0, 0.1961161345243454, 0.08506310731172562,
        0.9010388255119324, -0.4253155291080475, -0.17670825123786926,
        0.43373844027519226, 0.8835412859916687, -0.6000000238418579, 1.5, 2.75
      ],
      "lens": 0.10000000149011612,
      "aspect": 2.4000000953674316,
      "focus": 3.1124749183654785
    },
    {
      "name": "perspective-dof",
      "frame": [
        0.9805806875228882, -0.0, 0.1961161345243454, 0.08506310731172562,
        0.9010388255119324, -0.4253155291080475, -0.17670825123786926,
        0.43373844027519226, 0.8835412859916687, -0.6000000238418579, 1.5, 2.75
      ],
      "lens": 0.10000000149011612,
      "aspect": 2.4000000953674316,
      "focus": 3.1124749183654785,
      "aperture": 0.05000000074505806
    },
    {
      "name": "orthographic-sharp",
      "frame": [
        0.9756097197532654, -0.0, 0.2195121943950653, 0.08407647162675858,
        0.9237421154975891, -0.3736732006072998, -0.20277264714241028,
        0.3830150067806244, 0.9012117385864258, -0.5, 1.0, 2.0
      ],
      "orthographic": true,
      "lens": 0.029999999329447746,
      "aspect": 2.4000000953674316,
      "focus": 2.2192342281341553
    },
    {
      "name": "orthographic-dof",
      "frame": [
        0.9756097197532654, -0.0, 0.2195121943950653, 0.08407647162675858,
        0.9237421154975891, -0.3736732006072998, -0.20277264714241028,
        0.3830150067806244, 0.9012117385864258, -0.5, 1.0, 2.0
      ],
      "orthographic": true,
      "lens": 0.029999999329447746,
      "aspect": 2.4000000953674316,
      "focus": 2.2192342281341553,
      "aperture": 0.019999999552965164
    }
  ],
  "environments": [
    {
      "name": "sky",
      "emission": [0.5, 0.5, 0.5],
      "emission_tex": 0
    }
  ],
  "textures": [
    {
      "name": "sky",
      "uri": "textures/sky.hdr"
    },
    {
      "name": "floor",
      "uri": "textures/floor.png"
    }
  ],
  "materials": [
    {
      "name": "floor",
      "color": [0.699999988079071, 0.699999988079071, 0.699999988079071],
      "color_tex": 1
    },
    {
      "name": "largearealight1",
      "emission": [10.0, 10.0, 10.0]
    },
    {
      "name": "largearealight2",
      "emission": [10.0, 10.0, 10.0]
    },
    {
      "name": "sphere-volume-cloud",
      "type": "volume",
      "color": [0.6499999761581421, 0.6499999761581421, 0.6499999761581421],
      "scattering": [0.8999999761581421, 0.8999999761581421, 0.8999999761581421]
    },
    {
      "name": "sphere-volume-glass",
      "type": "refractive",
      "color": [1.0, 0.5, 0.5],
      "trdepth": 0.019999999552965164
    },
    {
      "name": "sphere-volume-jade",
      "type": "refractive",
      "color": [0.5, 0.5, 0.5],
      "scattering": [
        0.30000001192092896, 0.6000000238418579, 0.30000001192092896
      ]
    },
    {
      "name": "sphere-volume-jade2",
      "type": "refractive",
      "color": [0.5, 0.5, 0.5],
      "scattering": [
        0.30000001192092896, 0.6000000238418579, 0.30000001192092896
      ]
    },
    {
      "name": "sphere-volume-smoke",
      "type": "volume",
      "color": [0.5, 0.5, 0.5],
      "scattering": [
        0.20000000298023224, 0.20000000298023224, 0.20000000298023224
      ]
    },
    {
      "name": "bunny-volume-cloud",
      "type": "volume",
      "color": [0.6499999761581421, 0.6499999761581421, 0.6499999761581421],
      "scattering": [0.8999999761581421, 0.8999999761581421, 0.8999999761581421]
    },
    {
      "name": "bunny-volume-glass",
      "type": "refractive",
      "color": [1.0, 0.5, 0.5],
      "trdepth": 0.019999999552965164
    },
    {
      "name": "bunny-volume-jade",
      "type": "refractive",
      "color": [0.5, 0.5, 0.5],
      "scattering": [
        0.30000001192092896, 0.6000000238418579, 0.30000001192092896
      ]
    },
    {
      "name": "bunny-volume-jade2",
      "type": "refractive",
      "color": [0.5, 0.5, 0.5],
      "roughness": 0.10000000149011612,
      "scattering": [
        0.30000001192092896, 0.6000000238418579, 0.30000001192092896
      ]
    },
    {
      "name": "bunny-volume-smoke",
      "type": "volume",
      "color": [0.5, 0.5, 0.5],
      "scattering": [
        0.20000000298023224, 0.20000000298023224, 0.20000000298023224
      ]
    }
  ],
  "shapes": [
    {
      "name": "floor",
      "uri": "shapes/floor.ply"
    },
    {
      "name": "largearealight1",
      "uri": "shapes/largearealight1.ply"
    },
    {
      "name": "largearealight2",
      "uri": "shapes/largearealight2.ply"
    },
    {
      "name": "sphere",
      "uri": "shapes/sphere.ply"
    },
    {
      "name": "bunny",
      "uri": "shapes/bunny.ply"
    }
  ],
  "instances": [
    {
      "name": "floor",
      "shape": 0,
      "material": 0
    },
    {
      "name": "largearealight1",
      "frame": [
        0.8944271802902222, -0.0, 0.4472135901451111, 0.2873478829860687,
        0.766261100769043, -0.5746957659721375, -0.3426823318004608,
        0.6425293684005737, 0.6853646636009216, -0.800000011920929,
        1.600000023841858, 1.600000023841858
      ],
      "shape": 1,
      "material": 1
    },
    {
      "name": "largearealight2",
      "frame": [
        0.8944271802902222, 0.0, -0.4472135901451111, -0.2873478829860687,
        0.766261100769043, -0.5746957659721375, 0.3426823318004608,
        0.6425293684005737, 0.6853646636009216, 0.800000011920929,
        1.600000023841858, 1.600000023841858
      ],
      "shape": 2,
      "material": 2
    },
    {
      "name": "sphere-volume-cloud",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -0.4000000059604645, 0.0,
        0.0
      ],
      "shape": 3,
      "material": 3
    },
    {
      "name": "sphere-volume-glass",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -0.20000000298023224, 0.0,
        0.0
      ],
      "shape": 3,
      "material": 4
    },
    {
      "name": "sphere-volume-jade",
      "shape": 3,
      "material": 5
    },
    {
      "name": "sphere-volume-jade2",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.20000000298023224, 0.0,
        0.0
      ],
      "shape": 3,
      "material": 6
    },
    {
      "name": "sphere-volume-smoke",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.4000000059604645, 0.0,
        0.0
      ],
      "shape": 3,
      "material": 7
    },
    {
      "name": "bunny-volume-cloud",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -0.4000000059604645, 0.0,
        -0.4000000059604645
      ],
      "shape": 4,
      "material": 8
    },
    {
      "name": "bunny-volume-glass",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -0.20000000298023224, 0.0,
        -0.4000000059604645
      ],
      "shape": 4,
      "material": 9
    },
    {
      "name": "bunny-volume-jade",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        -0.4000000059604645
      ],
      "shape": 4,
      "material": 10
    },
    {
      "name": "bunny-volume-jade2",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.20000000298023224, 0.0,
        -0.4000000059604645
      ],
      "shape": 4,
      "material": 11
    },
    {
      "name": "bunny-volume-smoke",
      "frame": [
        1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.4000000059604645, 0.0,
        -0.4000000059604645
      ],
      "shape": 4,
      "material": 12
    }
  ]
}

=== zymk9/cmu15618_project/tests/features2/features2.json
{
  "asset": {
    "copyright": "Model by Fabio Pellacini from github.com/~xelatihy/yocto-gl",
    "generator": "Yocto/GL - https://github.com/xelatihy/yocto-gl",
    "version": "4.2"
  },
  "cameras": [
    {
      "name": "default",
      "frame": [
        0.8151804208755493,
        -0.0,
        0.579207181930542,
        0.16660168766975403,
        0.9577393531799316,
        -0.23447643220424652,
        -0.5547295212745667,
        0.28763750195503235,
        0.7807304263114929,
        -0.75,
        0.4000000059604645,
        0.8999999761581421
      ],
      "aspect": 2.4000000953674316,
      "focus": 1.2168092727661133
    }
  ],
  "environments": [
    {
      "name": "sky",
      "emission": [
        0.5,
        0.5,
        0.5
      ],
      "emission_tex": 0
    }
  ],
  "textures": [
    {
      "name": "sky",
      "uri": "textures/sky.hdr"
    },
    {
      "name": "floor",
      "uri": "textures/floor.png"
    },
    {
      "name": "uvgrid",
      "uri": "textures/uvgrid.png"
    },
    {
      "name": "bumpsdisplacement",
      "uri": "textures/bumpsdisplacement.png"
    }
  ],
  "shapes": [
    {
      "name": "arealight1",
      "uri": "shapes/arealight1.ply"
    },
    {
      "name": "arealight2",
      "uri": "shapes/arealight2.ply"
    },
    {
      "name": "floor",
      "uri": "shapes/floor.ply"
    },
    {
      "name": "sphere",
      "uri": "shapes/sphere.ply"
    },
    {
      "name": "suzannesubdiv",
      "uri": "shapes/suzannesubdiv.ply"
    },
    {
      "name": "hairball",
      "uri": "shapes/hairball.ply"
    },
    {
      "name": "displacedsubdiv",
      "uri": "shapes/displacedsubdiv.ply"
    },
    {
      "name": "cube",
      "uri": "shapes/cube.ply"
    },
    {
      "name": "hairballi",
      "uri": "shapes/hairballi.ply"
    }
  ],
  "subdivs": [
    {
      "name": "suzannesubdiv",
      "shape": 4,
      "uri": "subdivs/suzannesubdiv.obj",
      "subdivisions": 2,
      "catmullclark": true,
      "smooth": true
    },
    {
      "name": "displacedsubdiv",
      "shape": 6,
      "uri": "subdivs/displacedsubdiv.obj",
      "catmullclark": true,
      "smooth": true,
      "displacement": 0.025,
      "displacement_tex": 3
    }
  ],
  "materials": [
    {
      "name": "arealight1",
      "type": "matte",
      "emission": [
        20,
        20,
        20
      ],
      "color": [
        0,
        0,
        0
      ]
    },
    {
      "name": "arealight2",
      "type": "matte",
      "emission": [
        20,
        20,
        20
      ],
      "color": [
        0,
        0,
        0
      ]
    },
    {
      "name": "floor",
      "type": "matte",
      "color": [
        1,
        1,
        1
      ],
      "color_tex": 1
    },
    {
      "name": "uvgrid",
      "type": "glossy",
      "color": [
        1,
        1,
        1
      ],
      "roughness": 0.2,
      "color_tex": 2
    },
    {
      "name": "roughplastic",
      "type": "glossy",
      "color": [
        0.5,
        0.7,
        0.5
      ],
      "roughness": 0.2
    },
    {
      "name": "hair",
      "type": "matte",
      "color": [
        0.7,
        0.7,
        0.7
      ]
    }
  ],
  "instances": [
    {
      "name": "arealight1",
      "frame": [
        0.8944271802902222,
        -0.0,
        0.4472135901451111,
        0.27562475204467773,
        0.7874992489814758,
        -0.5512495040893555,
        -0.3521803617477417,
        0.6163156628608704,
        0.7043607234954834,
        -0.4000000059604645,
        0.800000011920929,
        0.800000011920929
      ],
      "shape": 0,
      "material": 0
    },
    {
      "name": "arealight2",
      "frame": [
        0.8944271802902222,
        0.0,
        -0.4472135901451111,
        -0.27562475204467773,
        0.7874992489814758,
        -0.5512495040893555,
        0.3521803617477417,
        0.6163156628608704,
        0.7043607234954834,
        0.4000000059604645,
        0.800000011920929,
        0.800000011920929
      ],
      "shape": 1,
      "material": 1
    },
    {
      "name": "floor",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0
      ],
      "shape": 2,
      "material": 2
    },
    {
      "name": "sphere-uvgrid",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        -0.4,
        0,
        0
      ],
      "shape": 3,
      "material": 3
    },
    {
      "name": "suzannesubdiv-roughplastic",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        -0.2,
        0,
        0
      ],
      "shape": 4,
      "material": 4
    },
    {
      "name": "hairball-hair",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.0,
        0,
        0
      ],
      "shape": 5,
      "material": 5
    },
    {
      "name": "displacedsubdiv-roughplastic",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.2,
        0,
        0
      ],
      "shape": 6,
      "material": 4
    },
    {
      "name": "cube-uvgrid",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.4,
        0,
        0
      ],
      "shape": 7,
      "material": 3
    },
    {
      "name": "hairballi-hair",
      "frame": [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0.0,
        0,
        0
      ],
      "shape": 8,
      "material": 5
    }
  ]
}
